### ISSUE TITLE
Finish rewrite

### ISSUE THREAD

**Issue by codeliner** [prooph/proophessor-do-symfony#14]
## TODO 
from #13

- [ ] Update README and Docs
- [ ] Get rid of templating component, see https://github.com/prooph/proophessor-do-symfony/pull/13#pullrequestreview-66517961
- [ ] Test different installation ways
- [ ] Release new bundle versions and require them in the demo 
- [ ] Reactivate reminder email service
- [ ] Test process managers (not working atm)
- [ ] Enable snapshots and snapshot projection
- [ ] Merge prooph-do and prooph-do-symfony
